
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "oliv")
Ingredient.create(name: "curaço")
Ingredient.create(name: "rhum")
Ingredient.create(name: "beer")
Ingredient.create(name: "sirop")
Ingredient.create(name: "water")
Ingredient.create(name: "orange")
Ingredient.create(name: "suggar")
Ingredient.create(name: "tequila")
Ingredient.create(name: "menthe")
